version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-hello
    ports:
      - "5000:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
