apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: algotest
spec:
  type: LoadBalancer  
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
